### ISSUE TITLE
Branches and version

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspyUI#10]
It would be nice to have a branch of the UI that works with the last release of hyperspy (proably after 0.8 released), a branch that works with the master branch of hyperspy and a branch that works with a "dev" branch that works with a hyperspy/UI branch with the latest modification not yet merged into hyperspy/master

**Comment by francisco-dlp** [comment]
On a similar subject: we would like to release HyperSpy 0.8 in the next few weeks. What do you think about shipping a preview of HyperSpy UI with the HyperSpy Bundle for Windows?

**Comment by vidartf** [comment]
@pburdet Yeah, forking of a "stable" build for latest version is a good idea. Other than that, the idea is for the UI to be able to check for hyperspy features at run time (which is also why I'm moving anything that is not a core functionality to plugins), and to be robust enough to continue running even if something goes wrong. Currently I find myself having to rescue sessions a lot via the console.

@francisco-dlp Not sure if it is quite stable enough, and there's still quite a bit of basic functionality missing. Personally I feel it's somewhere in alpha/beta territory. I'm not really that familiar with the user base, so I don't know how people would react to it in its current state. What would be needed to be able to bundle it in your view?

Currently I'm trying to clean up the internal framework, so that it is more robust/clear for other people, so that they can make contributions. The biggest crux at the moment is the partly-hacked together signal-to-figures tracking. It badly needs a refactoring. A different problem is that I have quite a bit of other work piling up now, so the time I can spend on this in the coming weeks is quite limited.

**Comment by vidartf** [comment]
PS: My biggest argument against releasing the UI too wide too early is that it can slow down the quick turnover that is needed in the initial phase to be able to refactor the internals. I'd like to make sure I get things right before I lose that flexibility. In other words, I don't want to quench it before it has got the right structure :)

**Comment by francisco-dlp** [comment]
> the idea is for the UI to be able to check for hyperspy features at run time

Coooool!!!

Regarding bundling it with HyperSpy 0.8, if we can make it happen in a maximum of 2-3 weeks, it'll be really nice. As long as you make it clear that it's in the early stages of development—maybe by having a warning popping up when starting it— it'll be ok. I don't think that you'll lose flexibility by releasing too early if you warn the users of the possibility of drastic changes in the future. The main concern are not HyperSpy current users—most of those are happy with scripting and probably will always prefer it to an UI—but the many users who will be attracted to the project if there is an UI in the works.

**Comment by pburdet** [comment]
Hyperspy UI works with master, that's great. Having the UI working with any branches is a really good thing.

I do agree with Francisco, having the UI for the next release is a great thinks. The main feature that we can expect from it are working nicely. We just need to be careful that the user is aware that it is a work in progress and major changes can be expected  in future release

**Comment by vidartf** [comment]
That sounds doable, but I guess it would be easier to discuss the final details in person. I'm coming to Cambridge the week before MSM, as I'm going to run some experiments there Thursday/Friday, but I'm arriving on Tuesday so we could use (part of) the Wednesday to discuss and do the necessary work? Does that fit with your schedules?

**Comment by francisco-dlp** [comment]
It seems a bit tight but, given that we'll be shipping HyperSpyUI as
alpha-grade software, it should be ok. If we go on with this plan then
HyperSpy 0.8 will be released on the 28th of March, is that ok? Is there
any PR that is highly desirable for nicely showcasing HyperSpyUI and
that is not merged yet?

**Comment by vidartf** [comment]
Well, I'll of course try to make sure I have a half-way polished version ready by then, so that it is mostly packaging and fine-polishing that would remain. Regarding PRs, I think the ROI stuff will probably be to big changes to be included in 0.8 (?), in which case I will house temporary widget classes in the hyperspyUI code. I definitively want to have a line-measure tool (to measure distances), as it's a staple for any microscopy UI, and preferably a line-profile tool. Other than that, there isn't really that much to showcase that depend on any PRs.

**Comment by francisco-dlp** [comment]
We can try to have the ROIs in time for 0.8, it's not 100% that we'll manage to do it but I think that it's worth trying. The line-profile tool may be a bit too ambitious for the available time span because, HyperSpy being HyperSpy, it should work seamlessly in n-dimensions.

**Comment by vidartf** [comment]
> We can try to have the ROIs in time for 0.8, it's not 100% that we'll manage to do it but I think that it's worth trying.

OK, I'll try to keep an eye out for what happens, and try to help out on what I can.

> The line-profile tool may be a bit too ambitious for the available time span because, HyperSpy being HyperSpy, it should work seamlessly in n-dimensions.

Well, to calculate the profile it's just a matter of interpolating a line in n dimensions given two points, but in terms of UI it would have to be in 2D or less for trivial input. For higher dimensions I think maybe the easiest would be to sequentially prompt for input of two ND points, but yeah, that will probably not be in time for 0.8.

**Comment by francisco-dlp** [comment]
I agree, the 2D case is the most useful for most users and it'll be great to have it in HyperSpy 0.8. In case that it helps, they have implemented the [feature in skimage](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/profile.py).

**Comment by vidartf** [comment]
Thanks, that makes it quite a bit easier, and should both simplify the code and be optimized well.
