### ISSUE TITLE
Rotate by 90 degrees is wrong angle

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#108]
Image -> Rotate seems to work fine, except for... um.. odd multiples of 90 degrees? Then it flips by an additional 180 degrees. Try stepping through 88 - 91 degrees to see.

**Comment by vidartf** [comment]
The multiples of 90 degrees rotation are "optimized" to avoid the blurring that occurs in the otherwise used ndimage rotation. Not surprised if that is a bit wrong. At least one of the 90deg multiples should give you what you want (so a workaround exists until it is fixed), but a more robust identification of the axes to operate on should be used.

A better solution is of course to merge the rotation method in the UI into the ongoing effort in hyperspy/hyperspy#1243.

**Comment by magnunor** [comment]
Just bumped into the same bug :)
